### ISSUE TITLE
A General-purpose NFT Marketplace

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/halogrants#29]
## Description
Build a general-purpose NFT marketplace with an eye on a modern UI providing a seamless user experience. It should include the following features:

- User login with Metamask
- Allow a user to put an NFT on sale at a fixed price with title and description
- Allow a user to change the price of his NFTs while on sale
- List/Filter NFTs available for sale and display the actual content
- Allow website visitors to buy NFTs
- Allow website visitors to search NFTs by free text on title and description

This bounty includes front-end, backend design and implementation and smart contracts design and implementation, integration with Metamask wallet via Web3.js. 
 
## Context
IoTeX is an EVM and Web3js compatible platform, and its mission is to connect the physical world to the _Metaverse_ using blockchain and the Internet-of-Trusted Things. There are many NFTs already deployed on the IoTeX mainnet such as the "_Ucam Pioneer NFT_" given to those who [pre-ordered a Ucam](https://ucam.iotex.io) before it was launched on Amazon, or the "_Burn Drop Ignite_" NFT, and more will be added in the future by upcoming dApps using trusted data from the real world like _[PebbleGo](https://pebblego.io)_ (see references below).

## Acceptance criteria
**Milestone 1 - Basic Functions** 
* [ ] Owner's Metamask login into his profile (show his own NFTs)
* [ ] Owner can put NFT for sale (fixed price)
* [ ] List all NFTs for sale and display content (images) 
* [ ] Filter NFTs list 
    - Price range
    - Author
    - Type of content
    - Recent/Pub date range
* [ ] Buy NFTs
* [ ] Search for NFTs
 
**Milestone 2 - Advanced Functions**
* [ ] Support NFTs of music/video/text/gift/file
* [ ] Support sell NFTs as an Auction and allow bids
* [ ] Improvement on UI/UX and performance
* [ ] A simple landing page

## Time estimation
3 weeks

## Reward

* [ ] Milestone I: 4000 USD (or 100,000 IOTX)
* [ ] Milestone 2: 4000 USD (or 100,000 IOTX)

## References
- [IoTeX Docs website](https://docs.iotex.io) 
- [Use Web3js Tools with IoTeX](https://docs.iotex.io/software-tools/ethereum-tools)
- [Block explorer](https://iotexscan.io)
- [Testnet Faucet](https://faucet.iotex.io/)
- [ioPay Wallet](https://iopay.iotex.io)
- [IoTeX ioctl Cli](https://docs.iotex.io/reference/ioctl-cli-reference)
## Follow Us

[iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 8000.0 USDT (8000.0 USD @ $1.0/USDT)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,109,677.81 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [oiclid](https://gitcoin.co/oiclid) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740?mutate_worker_action=approve&worker=oiclid) | [reject worker](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740?mutate_worker_action=reject&worker=oiclid))_.**

I am ready and able to start work building the marketplace based on requirements. I can start immediately.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740).

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 8000.0 USDT (8000.00 USD @ $1.0/USDT) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,090,060.64 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 8000.0 USDT (8000.00 USD @ $1.0/USDT) has been submitted by__:

 1. [@sirah09](https://gitcoin.co/sirah09)



@raullenchai please take a look at the submitted work:
* [PR](https://github.com/iotexproject/halogrants/issues/29) by @sirah09

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/29/100025740).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,884,330.07 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by deepface19** [comment]
when bounty get paid sir

**Comment by simonerom** [comment]
> when bounty get paid sir

Hey @deepface19 It seems your submission does not belong to our grant, or at least your NFT marketplace doesn’t seem to support IoTeX. Can you provide any link of a working demo for IoTeX?

**Comment by deepface19** [comment]
wait i create a new repo for a explain IOTEX

Pada tanggal Jum, 18 Jun 2021 00.09, Simone ***@***.***>
menulis:

**Comment by TheVanquiser** [comment]
done sir please check my project
