### ISSUE TITLE
[TBD] Review and improve IoTeX Docs

### ISSUE THREAD

**Issue by simonerom** [iotexproject/halogrants#32]
**Discuss**: Please join our [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) to ask any questions or reach out to `Simone_IoTeX` on Discord if you need any help.

**Follow Us**: [iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

## Bounty Description
We would like you to go through our documentation website at https://docs.iotex.io from a User/developer perspective and provide a report pointing out errors, inconsistencies, typos, dead links. Also go through the examples and tutorials and try them reporting what is not working, errors, outdated content etc... 

## Acceptance criteria
* [ ] Read carefully through every single section and try out all instructions to make sure there is no confusing content.
* [ ] Report as many issues as possible in your report
* [ ] If you have any, please report any suggestions about how you would improve the content

**Milestone 1**
* [ ] Provide a report with the list of relevant things to change/improve: for each item provide at least 
  - a screenshot of the relevant doc section
  - the actual link to get there
  - your notes about what's wrong/how to improve

## Reward

* [ ] Milestone I: TBD

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 15505.8593 IOTX (498.59 USD @ $0.03/IOTX)  attached to it as part of the iotexproject fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,747,400.50 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [bejarano-tech](https://gitcoin.co/bejarano-tech) has started work.**

To complete this task i will take this steps:

[ ] Go through our documentation website 
[ ] Provide a report pointing out errors, inconsistencies, typos and dead links. 
[ ] give you suggestions about how to improve the content.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [deosaju](https://gitcoin.co/deosaju) has started work.**

Reading carefully and updating upon finding something instresting.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [deosaju](https://gitcoin.co/deosaju) has started work.**

Keep on looking for something !

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).

**Comment by Deosaju** [comment]
Typo

1.It is now avalable in your laptop! in http://iopay.iotex.io/desktop/ Screenshot added
![desktop](https://user-images.githubusercontent.com/51228280/119259608-a5024f00-bbec-11eb-8404-05f603b4c113.png)

2.Note that is you encounter issues such as "action is not found", check for following reasons:     https://docs.iotex.io/more-resources/misc-tools
![Misc](https://user-images.githubusercontent.com/51228280/119259655-dbd86500-bbec-11eb-911a-621d1352d1c8.png)
Change use if instead of is and check for the following reasons

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 15505.8593 IOTX (500.54 USD @ $0.03/IOTX) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,759,430.49 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by mwood77** [comment]
@gitcoinbot didn't quote me correctly for my work submitted. Hence I'm posting here.

Work: [https://github.com/mwood77/IoTeX/tree/1.0.0](https://github.com/mwood77/IoTeX/tree/1.0.0)

![Screenshot 2021-05-27 at 15 23 08](https://user-images.githubusercontent.com/43637076/119833630-8dcea480-beff-11eb-94be-c05f89b070a4.png)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 15505.8593 IOTX (466.88 USD @ $0.03/IOTX) has been submitted by__:

 1. [@mwood77](https://gitcoin.co/mwood77)



@simonerom please take a look at the submitted work:
* [PR](https://github.com/mwood77/IoTeX/tree/1.0.0) by @mwood77

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,695,893.24 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by ries9112** [comment]
Just submitted my work. 

Here is my GitHub repository for the task: https://github.com/ries9112/IoTeX-Documentation-Review

And you can find my documentation/review here: https://ries9112.github.io/IoTeX-Documentation-Review/

Using the link above you should see a document like this with my complete review of all sections:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32306488/120088404-5998e680-c0ad-11eb-9e5f-50479f2e8d02.png">

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 1500.0 USDT (1500.00 USD @ $1.0/USDT)  attached to this issue has been approved & issued to @mwood77.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/32/100025753)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,248,217.44 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
