### ISSUE TITLE
[Draft] Build an "Infura-like" service for IoTeX

### ISSUE THREAD

**Issue by simonerom** [iotexproject/halogrants#43]
# Bounty Description
We would like to see a team building an **Infura-like** service for IoTeX, to provide the infrastructure for developers to easily develop and test their blockchain applications with simple and reliable access to a high-quality IoTeX API, without the need of deploying a full node.

# Context
The IoTeX ecosystem is growing by the day. While the cryptocurrency is on its way to climb the top 100 rankings, more and more developers are attracted by the benefits that IoTeX provides. A solid infrastructure for professional access to the IoTeX network is now a necessity. We welcome any solid team that wants to take over this challenge and build and maintain such a service, inspired by the great work that Infura does for Ethereum developers.  

# Acceptance criteria

**Milestone 1**
* [ ] Deploy the network of nodes, including load balancers, and perform load tests

**Milestone 2**
* [ ] Deploy the frontend for developers to buy access subscriptions
* [ ] Possibly provide a free tier for single developers/startups

# Time estimation

# Reward
## Milestone II: 5000 IOTX

# Misc/References
### Similar projects
- https://infura.io/
- https://www.alchemy.com/
- https://www.anyblockanalytics.com/
- https://www.quicknode.com/

# IoTeX Useful Links

**Discuss**: Please join our [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) to ask any questions or reach out to `Simone_IoTeX` on Discord if you need any help.

**Docs**: [IoTeX Docs](https://docs.iotex.io) | [Ethereum Compatibility](https://docs.iotex.io/software-tools/ethereum-tools) | [DID](https://docs.iotex.io/middleware-1/decentralized-identity) | [Full Nodes](https://community.iotex.io/t/official-iotex-delegates-thread/1263) 

**Follow Us**: [iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 10000.0 USDC (10000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,640,302.01 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 3 months from now.
Please review their action plans below:


**1) [lucasespinosa28](https://gitcoin.co/lucasespinosa28) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=approve&worker=lucasespinosa28) | [reject worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=reject&worker=lucasespinosa28))_.**

I use the Infura often and I running my own ETH a BTC node

I'll deploy the public nodes in servers with load-balance with rate limit and more than one region
the site will have multiples tiers, including the free tier. a dashboard  to show the requests  and I'll write the documentation with every methods support by the nodes

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325).

**Comment by gitcoinbot** [comment]
@lucasespinosa28 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by lucasespinosa28** [comment]
> @tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to ‘Open’ status. Please let us know if you have questions!
> 
> * [x]  reminder (3 days)
> * [ ]  escalation to mods (6 days)
> 
> Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

I installed a full node on my local machine and
was deployed on the server with load balance

I had the flu and found out I had a covid. I had already been vaccinated and I have no symptoms, Tuesday I have to leave the hospital, and I will continue the project

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by lucasespinosa28** [comment]
> @tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
> 
> * [x]  reminder (3 days)
> * [ ]  escalation to mods (6 days)
> 
> Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

I am working on this project.

**Comment by gitcoinbot** [comment]
@lucasespinosa28 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@lucasespinosa28 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
@tpscrpt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=1) | [3 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=3) | [5 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=5) | [10 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=10) | [100 days](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [fluffy9](https://gitcoin.co/fluffy9) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=approve&worker=fluffy9) | [reject worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=reject&worker=fluffy9))_.**

Will complete milestones 1 and 2

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [jdevstudios](https://gitcoin.co/jdevstudios) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=approve&worker=jdevstudios) | [reject worker](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325?mutate_worker_action=reject&worker=jdevstudios))_.**

I have worked on a similar projects and I have over 10 years of development experience, i'll get it done with in the description parameters.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/43/100026325).
