### ISSUE TITLE
[Draft] An algorithmic Stablecoin on IoTeX

### ISSUE THREAD

**Issue by simonerom** [iotexproject/halogrants#44]
# Bounty Description
Deploy a stablecoin on IoTeX, either an algorithmic or crypto collateralized stablecoin. Forks of MakerDAO/FEI/Ampleforth, and similar products are welcome.

# Context
Stablecoins are cryptocurrencies that are backed by other assets or benchmarks, and they are stable (or almost) in nature. Thanks to the benefits that stablecoins provide, from payments to financial services, many different stablecoin projects have been created in the crypto market, and more will be launched in the future.

# Acceptance criteria

**Milestone 1**
* [ ] Deploy the contracts

**Milestone 2**
* [ ] Deploy the website

# Reward
## 4000 USD
* [ ] Milestone I: 2000 USD
* [ ] Milestone II: 2000 USD

# Misc/References
Similar projects:
- https://www.ampleforth.org/
- https://makerdao.com/
- https://fei.money/

# IoTeX Useful Links

**Discuss**: Please join our [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) to ask any questions or reach out to `Simone_IoTeX` on Discord if you need any help.

**Docs**: [IoTeX Docs](https://docs.iotex.io) | [Ethereum Compatibility](https://docs.iotex.io/software-tools/ethereum-tools) | [DID](https://docs.iotex.io/middleware-1/decentralized-identity) | [Full Nodes](https://community.iotex.io/t/official-iotex-delegates-thread/1263) 

**Follow Us**: [iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 5000.0 USDC (5000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/44/100026326).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/44/100026326).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,645,302.01 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 264 years, 1 month from now.
Please review their action plans below:


**1) [nasrudin921002](https://gitcoin.co/nasrudin921002) has started work.**

Menjadikan ini lebih baik dari pada yang terbaik
**2) [yowgibeer](https://gitcoin.co/yowgibeer) has started work.**

Deploy the contracts


Deploy the website
**3) [elhamne](https://gitcoin.co/elhamne) has started work.**

I'll deploy contracts and website
**4) [magro7](https://gitcoin.co/magro7) has started work.**

I don't know whaat can say  I'm new here and don't know how it works
**5) [thrasher33](https://gitcoin.co/thrasher33) has started work.**

Time will tell.   This is new for me and I'm learning as I go.   Hoping this turns into an education and experience
**6) [andhumon](https://gitcoin.co/andhumon) has started work.**

I think working about 5 hours is enough for this job.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/26326).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 5000.0 USDC (5000.00 USD @ $1.0/USDC) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/iotexproject/halogrants/44/100026326)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/iotexproject/halogrants/44/100026326).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,652,132.84 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
